language: php

php:
  - 5.4
  - 5.5

install:
  - composer install --dev --no-interaction --prefer-source

before_script:
  - vendor/bin/phing prepare-test -Dversion=HEAD -Dlanguage=de,de_x_sie

script:
  - vendor/bin/phing test -Dversion=HEAD -Dlanguage=de
  - vendor/bin/phing test -Dversion=HEAD -Dlanguage=de_x_sie
