language: php

php:
  - 5.3.3
  - 5.5

install:
  - sudo apt-get install parallel
  - php composer.phar install --dev --no-interaction --prefer-source

script:
  - find . -type f -name "*.php" | parallel --gnu --keep-order 'php -l {} > /dev/null' || exit 1
  - php vendor/bin/PhpbbTranslationValidator.php validate de --phpbb-version=3.0 --language-dir=language
  - php vendor/bin/PhpbbTranslationValidator.php validate de_x_sie --phpbb-version=3.0 --language-dir=language
