language: php

php:
  - 5.3.3
  - 5.5

install:
  - php composer.phar install --dev --no-interaction --prefer-source

script:
  - vendor/bin/phing -Dlanguage=de -Dversion=HEAD
  # Disable de-x-sie: - vendor/bin/phing -Dlanguage=de_x_sie -Dversion=HEAD
